---
- name: Play Ping
  hosts: host
  become: yes
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Ping all good!

