---
- name: Add SSH public key using Shell
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
    - name: Inject SSH public key via AWS SSM
      ansible.builtin.shell: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:AllowAccess,Values=true" \   #Change based on tag you specified
          --parameters '{"commands":["/bin/echo -e \"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP9RDbcwxWls1oJsicyYYoZulaeUm1AZ+krAb+IdFE3v ec2-user@ip-172-31-30-194.ec2.internal\" >> /home/ec2-user/.ssh/authorized_keys"]}' \
          --region us-east-1  
      register: ssm_result
    - name: Display the SSM command result
      debug:
        var: ssm_result
